dist: trusty
sudo: false

language: node_js
node_js:
  - "14"

branches:
  only:
    - main

notifications:
  email: false

addons:
  chrome: stable # have Travis install Chrome stable.

cache:
  directories:
    - ./node_modules

install:
  - npm install codecov -g
  - npm ci --ignore-scripts

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
  # Setting watch flag to false indicates to terminate after only one run.
  # --no-progress do not print progress messages.
  # ChromeHeadless run test is a version of Chrome created for automated testing and server environments. 

before_deploy:
  - npm run build -- --prod --base-href /angular-base-project/


deploy:

  # see https://docs.travis-ci.com/user/deployment/pages
  - provider: pages # Travis CI will deploy the static files to GitHub Pages after a successful build.
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/ps-store-app
    on:
      branch: main
  # see https://docs.travis-ci.com/user/deployment/s3
  - provider: s3
    skip_cleanup: true
    access_key_id: $S3_ACCESS_KEY_ID 
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "inigual-bucket"
    local_dir: dist/ps-store-app
    on:
      branch: main