dist: trusty
sudo: false

language: node_js
node_js:
  - "14"

branches:
  only:
    - main

notifications:
  email: false

addons:
  chrome: stable # have Travis install Chrome stable.

cache:
  directories:
    - ./node_modules

install:
  - npm install
  # - npm install codecov -g
  # - npm ci --ignore-scripts

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless

after_success:
  - codecov

before_deploy:
  - npm run build -- --prod --base-href /ps-store-app/

# script:
#   # run build script specified in package.json
#   - npm i webdriver-manager
#   - npm run ci
#   # call script for deploying of produced artifacts
#   - bash ./.travis-deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ps-store-app
  on:
    branch: main

